<a href="https://colab.research.google.com/github/sanku232006/ML-Practical/blob/main/Practical_No_3_EE_519.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [ ]:
file = pd.read_csv("/content/wireless_signal_quality_dataset.csv")


In [ ]:
print(file.head())

   Signal_Strength_dBm  SNR_dB  Interference_dB  Distance_m  Frequency_GHz  \
0                  -41       6                0         257            5.0   
1                  -86      25               20         134            2.4   
2                  -73      27                0         385            2.4   
3                  -57       5                0         255            5.0   
4                  -87      15               24          61            5.0   

   Channel_Bandwidth_MHz  Noise_Floor_dBm  Connected_Devices  \
0                    160             -100                 24   
1                    160              -96                 41   
2                     20              -72                 13   
3                    160              -86                  9   
4                     20              -79                 32   

   Estimated_Throughput_Mbps Quality  
0                         18    Poor  
1                         55    Poor  
2                         81 

In [ ]:
print(file.tail())

    Signal_Strength_dBm  SNR_dB  Interference_dB  Distance_m  Frequency_GHz  \
95                  -75      37               11          17            2.4   
96                  -88      11               18         231            5.0   
97                  -57       6               27         460            5.0   
98                  -49      25               24         298            2.4   
99                  -46       8               29         423            5.0   

    Channel_Bandwidth_MHz  Noise_Floor_dBm  Connected_Devices  \
95                    160              -80                 34   
96                     20              -90                 25   
97                    160              -76                 24   
98                     20              -78                 39   
99                     40              -71                 16   

    Estimated_Throughput_Mbps Quality  
95                        100    Fair  
96                         15    Poor  
97            

In [ ]:
print(file.isnull().sum())

Signal_Strength_dBm          0
SNR_dB                       0
Interference_dB              0
Distance_m                   0
Frequency_GHz                0
Channel_Bandwidth_MHz        0
Noise_Floor_dBm              0
Connected_Devices            0
Estimated_Throughput_Mbps    0
Quality                      0
dtype: int64


In [ ]:
label_encoder = LabelEncoder()
file['Quality']= label_encoder.fit_transform(file['Quality'])
print(file['Quality'])

0     3
1     3
2     1
3     3
4     3
     ..
95    1
96    3
97    3
98    1
99    3
Name: Quality, Length: 100, dtype: int64


In [ ]:
X =file.drop('Quality', axis=1)
y = file['Quality']

In [ ]:
X = pd.get_dummies(X, drop_first=True)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [ ]:
# Train-Test Split
#-------------------

x_train , x_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)
#

In [ ]:
# Feature Scaling
#------------------------------

scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

#----------------------------
# Train logistics Regression Model
#-----------------------------

model = LogisticRegression()
model.fit(x_train,y_train)

#--------------------------
# Make Prediction
#--------------------------

y_pred = model.predict(x_test)



In [ ]:


# Evaluation
#--------------------------

print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report: ")
print(classification_report(y_test, y_pred))


Accuracy:
0.65

Confusion Matrix:
[[0 0 1 0]
 [0 4 0 2]
 [0 2 1 0]
 [0 2 0 8]]

Classification Report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.67      0.57         6
           2       0.50      0.33      0.40         3
           3       0.80      0.80      0.80        10

    accuracy                           0.65        20
   macro avg       0.45      0.45      0.44        20
weighted avg       0.62      0.65      0.63        20



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
